apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-user
spec:
  selector:
    matchLabels:
      app: se-user
  replicas: 1
  template:
    metadata:
      labels:
        app: se-user
    spec:
      containers:
        - name: se-user
          image: jerreeey/usermanagement:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://se-user-mongo:27017/dev